---
title: "STAT 184 Final Project"
subtitle: "NYC AirBnb Data"
author: "Anna Leon"
output: html_notebook
---

## Front Matter

```{r}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(DataComputing)
library(readr)
library(dplyr)
```

## Data Access

```{r}
NYC <- read_csv("AB_NYC_2019.csv")

head(NYC)
names(NYC)
```

```{r}
glimpse(NYC) 
```

## Data Wrangling

I am dropping variables id, host_name, last_review, and minimum_nights because they are not relevant to my analysis.
```{r}
NewNYC <-
  NYC %>%
    select(name, host_id, neighbourhood, neighbourhood_group, latitude, longitude, room_type, price, number_of_reviews, reviews_per_month, calculated_host_listings_count, availability_365)
NewNYC
```

```{r}
NewNYC %>%
  group_by(host_id) %>%
  summarise(listings = n()) %>%
  arrange(desc(listings))
```

```{r}
BoroughAvgPrice <-
  NewNYC %>%
    group_by(borough = neighbourhood_group) %>%
    summarise(avg_price = round(mean(price, na.rm=TRUE))) %>%
    arrange(desc(avg_price))
BoroughAvgPrice
```

```{r}
NYCwAvg <-
  NewNYC %>%
    left_join(BoroughAvgPrice, by = c("neighbourhood_group" = "borough")) %>%
    rename(avg_price_in_borough = avg_price)
NYCwAvg
```

```{r}
NeighborhoodAvgPrice <-
  NewNYC %>%
    group_by(neighbourhood) %>%
    summarise(avg_price = round(mean(price, na.rm=TRUE))) %>%
    arrange(desc(avg_price))

HoodinBorough <-
  NewNYC %>%
    group_by(neighbourhood_group, neighbourhood) %>%
    summarise(count = n())

NeighborhoodsInfo <-
  NeighborhoodAvgPrice %>%
    left_join(HoodinBorough)

NeighborhoodsInfo
```

### "Cozy" Airbnbs

Now, I will be investigating the difference between price and availability of airbnbs that do not have the word cozy in their title with those that do.

```{r}
CozyAirbnbs <-
  NewNYC %>%
    filter(grepl("cozy", name, ignore.case = TRUE))

NotCozyAirbnbs <-
  NewNYC %>%
    filter(!grepl("cozy", name, ignore.case = TRUE))

CozyAirbnbs
NotCozyAirbnbs

CozyAirbnbs %>%
  summarise(ave_cost = round(mean(price, na.rm = TRUE), 2))

NotCozyAirbnbs %>%
  summarise(ave_cost = round(mean(price, na.rm = TRUE), 2))

CozyAirbnbs %>%
  summarise(ave_availability = round(mean(availability_365, na.rm = TRUE)))

NotCozyAirbnbs %>%
  summarise(ave_availability = round(mean(availability_365, na.rm = TRUE)))
```


## Data Visualization

```{r}
NeighborhoodsInfo$neighbourhood <- factor(NeighborhoodsInfo$neighbourhood,levels = c("Fort Wadsworth", "Woodrow", "Tribeca", "Sea Gate", "Riverdale"))

NeighborhoodsInfo %>%
  head(5) %>%
  ggplot(aes(x=neighbourhood, y=avg_price)) + 
  geom_point(aes(size=count)) +
  ggtitle("5 Most Expensive Neighborhoods for Airbnbs")
```


